### ISSUE TITLE
Require nightly build Kicad to open.

### ISSUE THREAD

**Issue by dwhacks** [rocketscream/TinyReflowController#1]
I'm on Linux Mint, and when trying to open the schematic file in kicad it says my version is to old! I have the "newest" stable, which leads me to believe this was made in a nightly (which gave me issues when I tried nightlies a year ago).

Any chance we could get Gerbers, or even an oshpark shared project?

**Comment by rocketscream** [comment]
Hi @dwhacks,

Yes, it is indeed designed in nightly builds (couldn't stop myself). I just added the gerber files in latest commit of 69a41e7. I no longer use OSHPark service (last used close to 5 years ago), so I'm not sure how the settings (like the silkscreen minimum line thickness, edge copper distance limit) would affect the board produced. But, board was designed with 10 mil minimum track and 10 mil minimum clearance except the ATtiny1634R QFN chip (I believe it needs 8 mil clearance in between pads).

**Comment by dwhacks** [comment]
Thanks! That mostly works, except for the slots in the USB connector, but thats not a big deal. Any chance you could post up a BOM too? Or should I just wait for the finished boards to be in stock again at rocketscream?

I guess I could install a nightly kicad on a different machine... But maybe this will benefit others too?
