### ISSUE TITLE
Controller gets stuck at preheat stage

### ISSUE THREAD

**Issue by fifteenhex** [rocketscream/TinyReflowController#2]
My controller worked once but now it's starting the preheat stage according to the screen, the temp gets up to ~148c, it starts turning the elements on and off to hold that temperature and then does nothing else. The graph shows it holding that temperature for a few minutes and it never jumps into the soak stage.

I can adjust the preheat min value so that it goes into soak at 148c instead but I think there should be some sort of timer to abort the whole process if a stage takes too long.

**Comment by rocketscream** [comment]
This is due to the oven unable to retain the heat. Try insulating the oven a little and usually that helps. 

But, a very good point on the timer. Will implement it on the next firmware release.

**Comment by fifteenhex** [comment]
I'll try adding some more insulation.
If I get time I'll implement a timer that aborts the reflow process if it takes too long and send you a PR.
